services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    extra_hosts:  # adds hostname mappings to the container network interface configuration
      - "localhost:host-gateway"  # allow nodejs-api to access zitadel via localhost
  backend:
    build: ./backend
    ports:
      - "3000:3000"
